package glorydark.wardensystem.forms;

public enum FormType {
    WardenMain,
    WardenDealBugReportList,
    WardenDealByPassReportList,
    WardenDealBugReport,
    WardenDealByPassReport,
    WardenPersonalInfo,
    WardenMailBox,
    WardenPunish,

    WardenPunishType,
    WardenTools,
    WardenTeleportTools,
    WardenPardon,
    PlayerMain,
    PlayerReportMain,
    PlayerBugReport,
    PlayerByPassReport,
    PlayerMailboxMain,
    PlayerMailboxInfo,
    DealBugReportReturn,
    WardenPunishReturn,
    AdminAddWardenReturn,
    AdminRemoveWardenReturn,
    DealByPassReportReturn,
    WardenStatusCheckReturn,
    WardenModifyOperatorReturn,
    RecentProfile,
    PlayerStatus,
    AdminManageType,
    AdminAddWarden,
    AdminRemoveWarden,
    WardenStatistics
}
